export const PRODUCTS_GET_ALL = "PRODUCTS_GET_ALL";
export const PRODUCT_GET_BY_ID = "PRODUCT_GET_BY_ID";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const PRODUCT_EDIT = "PRODUCT_EDIT";

// Action for Thunks

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCC = "FETCH_PRODUCTS_SUCC";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
